version: "3.8"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/config/openmed.json
    volumes:
      - "$PWD/config:/tmp/config"
    networks:
      - keycloak_net

networks:
  keycloak_net: