version: "3.8"
services:


  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/config/openmed.json
      KEYCLOAK_WELCOME_THEME: openmed
      KEYCLOAK_DEFAULT_THEME: openmed
    volumes:
      - "$PWD/config:/tmp/config"
      - "$PWD/config/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml"
      - "$PWD/themes/openmed:/opt/jboss/keycloak/themes/openmed"
    networks:
      - keycloak-net

networks:
  keycloak-net: