version: "3.8"
services:

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/config/openmed.json
    volumes:
      - "$PWD/config:/tmp/config"
    networks:
      - keycloak-net
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - keycloak-net

networks:
  keycloak-net: